export type Category = 'ordinateurs' | 'telephones' | 'accessoires';

export interface Product {
  id: string;
  name: string;
  category: Category;
  subcategory: string;
  price: number;
  originalPrice?: number;
  description: string;
  features: string[];
  image: string;
  badge?: string;
  stock: number;
  rating: number;
  reviews: number;
}

export const products: Product[] = [
  // ===== ORDINATEURS =====
  {
    id: 'ord-001',
    name: 'MacBook Pro 14"',
    category: 'ordinateurs',
    subcategory: 'Laptops',
    price: 1899000,
    originalPrice: 2100000,
    description: 'Le MacBook Pro 14" avec puce M3 Pro offre des performances exceptionnelles pour les professionnels créatifs.',
    features: ['Puce Apple M3 Pro', 'RAM 18 Go', 'SSD 512 Go', 'Écran Liquid Retina XDR 14"', 'Autonomie 18h', 'Ports Thunderbolt 4'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
    badge: 'Nouveau',
    stock: 12,
    rating: 4.9,
    reviews: 347,
  },
  {
    id: 'ord-002',
    name: 'Dell XPS 15',
    category: 'ordinateurs',
    subcategory: 'Laptops',
    price: 1450000,
    originalPrice: 1600000,
    description: 'Le Dell XPS 15 combine puissance et élégance pour une productivité maximale.',
    features: ['Intel Core i7-13700H', 'RAM 16 Go DDR5', 'SSD 512 Go NVMe', 'Écran OLED 15.6" 4K', 'RTX 4060 8 Go', 'Windows 11 Pro'],
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    badge: 'Promo',
    stock: 8,
    rating: 4.7,
    reviews: 215,
  },
  {
    id: 'ord-003',
    name: 'HP Pavilion 15',
    category: 'ordinateurs',
    subcategory: 'Laptops',
    price: 650000,
    description: 'Un ordinateur portable fiable et abordable pour les étudiants et la bureautique.',
    features: ['AMD Ryzen 5 7530U', 'RAM 8 Go', 'SSD 256 Go', 'Écran Full HD 15.6"', 'Autonomie 8h', 'Windows 11 Home'],
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    stock: 20,
    rating: 4.3,
    reviews: 128,
  },
  {
    id: 'ord-004',
    name: 'iMac 24"',
    category: 'ordinateurs',
    subcategory: 'Desktops',
    price: 1750000,
    description: "L'iMac 24\" avec puce M3 – un chef-d'œuvre alliant performance et design épuré.",
    features: ['Puce Apple M3', 'RAM 16 Go', 'SSD 512 Go', 'Écran Retina 4.5K 24"', 'Caméra FaceTime 12 MP', 'Magic Keyboard + Mouse'],
    image: 'https://images.unsplash.com/photo-1527443224154-c4a573d5e030?w=600&q=80',
    badge: 'Populaire',
    stock: 6,
    rating: 4.8,
    reviews: 289,
  },
  {
    id: 'ord-005',
    name: 'Lenovo ThinkPad X1 Carbon',
    category: 'ordinateurs',
    subcategory: 'Laptops',
    price: 1200000,
    description: 'Le ThinkPad X1 Carbon est le laptop business ultime – léger, robuste et puissant.',
    features: ['Intel Core i7-1365U', 'RAM 16 Go LPDDR5', 'SSD 1 To NVMe', 'Écran IPS 14" FHD+', 'Poids 1.12 kg', 'Certification MIL-SPEC'],
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&q=80',
    stock: 10,
    rating: 4.8,
    reviews: 176,
  },
  {
    id: 'ord-006',
    name: 'Asus ROG Strix G15',
    category: 'ordinateurs',
    subcategory: 'Gaming',
    price: 1350000,
    originalPrice: 1500000,
    description: "PC portable gaming haute performance avec écran 165Hz pour une fluidité maximale.",
    features: ['AMD Ryzen 9 7945HX', 'RAM 32 Go DDR5', 'SSD 1 To NVMe', 'RTX 4070 8 Go', 'Écran 15.6" 165Hz', 'RGB Aura Sync'],
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80',
    badge: 'Gaming',
    stock: 7,
    rating: 4.7,
    reviews: 203,
  },

  // ===== TÉLÉPHONES =====
  {
    id: 'tel-001',
    name: 'iPhone 16 Pro',
    category: 'telephones',
    subcategory: 'Apple',
    price: 1200000,
    originalPrice: 1350000,
    description: "L'iPhone 16 Pro redéfinit la photographie mobile avec son système de caméra ProCamera.",
    features: ['Puce A18 Pro', 'Caméra 48 MP + 48 MP Ultra Wide + 12 MP Téléobjectif', 'Dynamic Island', 'Écran Super Retina XDR 6.3"', 'Titanium Design', '5G'],
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80',
    badge: 'Nouveau',
    stock: 25,
    rating: 4.9,
    reviews: 512,
  },
  {
    id: 'tel-002',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'telephones',
    subcategory: 'Samsung',
    price: 1100000,
    originalPrice: 1250000,
    description: 'Le Galaxy S24 Ultra avec S Pen intégré, pour une créativité et une productivité sans limites.',
    features: ['Snapdragon 8 Gen 3', 'RAM 12 Go', 'Stockage 256 Go', 'Caméra 200 MP', 'S Pen intégré', 'Écran 6.8" Dynamic AMOLED'],
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80',
    badge: 'Populaire',
    stock: 18,
    rating: 4.8,
    reviews: 423,
  },
  {
    id: 'tel-003',
    name: 'Xiaomi 14',
    category: 'telephones',
    subcategory: 'Xiaomi',
    price: 620000,
    description: 'Le Xiaomi 14 offre des performances flagship à un prix accessible.',
    features: ['Snapdragon 8 Gen 3', 'RAM 12 Go', 'Stockage 256 Go', 'Triple caméra Leica', 'Charge rapide 90W', 'Écran AMOLED 6.36"'],
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
    stock: 30,
    rating: 4.6,
    reviews: 287,
  },
  {
    id: 'tel-004',
    name: 'Google Pixel 9 Pro',
    category: 'telephones',
    subcategory: 'Google',
    price: 950000,
    description: 'Le meilleur appareil photo Android avec Google AI intégré.',
    features: ['Puce Google Tensor G4', 'RAM 16 Go', 'Stockage 128 Go', 'Caméra 50 MP + Télézoom 5x', 'Google AI exclusif', 'Android 15'],
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
    stock: 14,
    rating: 4.7,
    reviews: 198,
  },
  {
    id: 'tel-005',
    name: 'OnePlus 12',
    category: 'telephones',
    subcategory: 'OnePlus',
    price: 680000,
    originalPrice: 750000,
    description: 'OnePlus 12 – la vitesse redéfinie avec une charge 100W ultra-rapide.',
    features: ['Snapdragon 8 Gen 3', 'RAM 12 Go LPDDR5X', 'Stockage 256 Go', 'Caméra Hasselblad 50 MP', 'Charge SuperVOOC 100W', 'Écran 6.82" 120Hz'],
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&q=80',
    badge: 'Promo',
    stock: 22,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 'tel-006',
    name: 'Samsung Galaxy A55',
    category: 'telephones',
    subcategory: 'Samsung',
    price: 390000,
    description: 'Smartphone milieu de gamme avec excellente autonomie et beau design.',
    features: ['Exynos 1480', 'RAM 8 Go', 'Stockage 128 Go', 'Triple caméra 50 MP', 'Batterie 5000 mAh', 'IP67'],
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&q=80',
    stock: 35,
    rating: 4.5,
    reviews: 342,
  },

  // ===== ACCESSOIRES =====
  {
    id: 'acc-001',
    name: 'AirPods Pro 2ème Génération',
    category: 'accessoires',
    subcategory: 'Audio',
    price: 280000,
    originalPrice: 320000,
    description: 'Réduction de bruit active de nouvelle génération pour une immersion totale.',
    features: ['Réduction de bruit active H2', 'Mode Transparence', 'Audio Spatial', 'Autonomie 6h + 30h boîtier', 'Résistance IP54', 'MagSafe'],
    image: 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=600&q=80',
    badge: 'Best Seller',
    stock: 50,
    rating: 4.8,
    reviews: 678,
  },
  {
    id: 'acc-002',
    name: 'Sony WH-1000XM5',
    category: 'accessoires',
    subcategory: 'Audio',
    price: 320000,
    originalPrice: 380000,
    description: 'Le meilleur casque à réduction de bruit du marché selon les experts.',
    features: ['Réduction de bruit leader industrie', 'Autonomie 30 heures', 'Charge rapide 3 min = 3h', 'Multipoint 2 appareils', 'Appels cristallins', 'Pliable'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    badge: 'Top Rated',
    stock: 28,
    rating: 4.9,
    reviews: 845,
  },
  {
    id: 'acc-003',
    name: 'Chargeur MagSafe 15W',
    category: 'accessoires',
    subcategory: 'Chargeurs',
    price: 45000,
    description: 'Charge sans fil magnétique ultra-rapide pour iPhone 12 et versions ultérieures.',
    features: ['Puissance 15W', 'Compatible MagSafe', 'Charge sans fil Qi', 'Câble USB-C tressé 1m', 'Design compact', 'Original Apple'],
    image: 'https://images.unsplash.com/photo-1610438235354-a6ae5528a12d?w=600&q=80',
    stock: 80,
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 'acc-004',
    name: 'Coque iPhone 16 Pro Premium',
    category: 'accessoires',
    subcategory: 'Coques',
    price: 25000,
    description: 'Protection maximale avec un design élégant pour votre iPhone 16 Pro.',
    features: ['Matière Aramid Fiber', 'Protection militaire MIL-SPEC', 'Compatible MagSafe', 'Bords surélevés', 'Ultra-mince 0.8mm', 'Garantie 2 ans'],
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80',
    stock: 100,
    rating: 4.5,
    reviews: 167,
  },
  {
    id: 'acc-005',
    name: 'SSD Externe Samsung T7 1To',
    category: 'accessoires',
    subcategory: 'Stockage',
    price: 120000,
    originalPrice: 145000,
    description: 'SSD externe ultra-rapide et portable – vos données sécurisées partout.',
    features: ['Capacité 1 To', 'Vitesse lecture 1050 Mo/s', 'Interface USB 3.2 Gen2', 'Chiffrement AES 256-bit', 'Résistance aux chocs', 'Compatible PC/Mac/Android'],
    image: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80',
    badge: 'Promo',
    stock: 40,
    rating: 4.7,
    reviews: 456,
  },
  {
    id: 'acc-006',
    name: 'Hub USB-C 7-en-1',
    category: 'accessoires',
    subcategory: 'Connectivité',
    price: 55000,
    description: 'Transformez votre USB-C en hub complet avec 7 ports essentiels.',
    features: ['HDMI 4K 60Hz', '2x USB-A 3.0', 'USB-C PD 100W', 'Lecteur SD/MicroSD', 'Ethernet Gigabit', 'Aluminium premium'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    stock: 60,
    rating: 4.4,
    reviews: 189,
  },
  {
    id: 'acc-007',
    name: 'Samsung Galaxy Watch 7',
    category: 'accessoires',
    subcategory: 'Montres connectées',
    price: 290000,
    originalPrice: 340000,
    description: 'Montre intelligente avec suivi santé avancé et design sportif.',
    features: ['Écran AMOLED 1.47"', 'Suivi santé 24/7', 'GPS intégré', 'Autonomie 40h', 'Résistance 5ATM', 'Samsung Health'],
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80',
    badge: 'Nouveau',
    stock: 22,
    rating: 4.6,
    reviews: 213,
  },
  {
    id: 'acc-008',
    name: 'Clavier Mécanique Logitech MX Keys',
    category: 'accessoires',
    subcategory: 'Claviers',
    price: 150000,
    description: 'Clavier mécanique sans fil premium pour une frappe précise et confortable.',
    features: ['Switches Brown silencieux', 'Rétroéclairage intelligent', 'Bluetooth + USB', 'Connecte 3 appareils', 'Autonomie 10 jours', 'Compatible Mac/Windows'],
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    stock: 35,
    rating: 4.7,
    reviews: 298,
  },
  {
    id: 'acc-009',
    name: 'Écran 4K LG UltraFine 27"',
    category: 'accessoires',
    subcategory: 'Moniteurs',
    price: 480000,
    originalPrice: 550000,
    description: "Moniteur 4K Nano IPS pour une qualité d'image professionnelle.",
    features: ['Résolution 4K 3840x2160', 'Nano IPS 98% DCI-P3', 'USB-C 96W', 'Taux de rafraîchissement 144Hz', 'HDR 600', 'Pied réglable ergonomique'],
    image: 'https://images.unsplash.com/photo-1527443224154-c4a573d5e030?w=600&q=80',
    badge: 'Promo',
    stock: 15,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 'acc-010',
    name: 'Power Bank Anker 20000mAh',
    category: 'accessoires',
    subcategory: 'Batteries',
    price: 65000,
    description: 'Batterie externe haute capacité pour recharger tous vos appareils en déplacement.',
    features: ['Capacité 20000 mAh', 'Charge rapide 65W', 'Ports USB-C + USB-A', 'Technologie PowerIQ', 'Poids 440g', 'Câble intégré'],
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80',
    stock: 75,
    rating: 4.7,
    reviews: 523,
  },
];

export const getProductsByCategory = (category: Category): Product[] =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string): Product | undefined =>
  products.find((p) => p.id === id);

export const getFeaturedProducts = (): Product[] =>
  products.filter((p) => p.badge).slice(0, 8);

export const formatPrice = (price: number): string =>
  new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'XOF', maximumFractionDigits: 0 }).format(price);

export const categoryInfo = {
  ordinateurs: {
    label: 'Ordinateurs',
    description: 'Laptops, Desktops et PC Gaming',
    icon: '💻',
    color: 'blue',
  },
  telephones: {
    label: 'Téléphones',
    description: 'Smartphones toutes marques',
    icon: '📱',
    color: 'purple',
  },
  accessoires: {
    label: 'Accessoires',
    description: 'Audio, Chargeurs, Câbles et plus',
    icon: '🎧',
    color: 'emerald',
  },
};
